version: '3'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/backend/
      - ./data:/backend/
    ports:
      - 8000:8000
    networks:
      - backend


  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/frontend/
      - /frontend/node_modules/
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    networks:
      - backend

networks:
  backend:
    driver: bridge
